twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # Render Login form after `Access Denied` Exception
    exception_controller: App\Controller\CustomExceptionController::showAction
